services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      # Host harus disesuaikan dengan nama service MySQL, yaitu 'db'
      - PMA_HOST=db
      # Anda dapat menggunakan nama pengguna yang Anda definisikan di layanan 'db'
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - db

# Names our volume
volumes:
  my-db: null
